
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Service\LevelCalculatorService: ~

  App\Service\RssFeedService:
    arguments:
      $httpClient: '@http_client'
      $feedUrl: '%rss.feed_url%'

  # Chargement automatique des services dans src/
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
